package com.psychosim.simulation.domain.model;

public enum AttemptEventType {
    ATTEMPT_STARTED,
    NODE_ENTERED,
    DECISION_SELECTED,
    PROHIBITED_DECISION_SELECTED,
    WORLD_POSITION_UPDATED,
    MAP_INTERACTION_OPENED,
    TOOL_USED,
    REFLECTION_SAVED,
    SAFE_EXIT_REQUESTED,
    ATTEMPT_COMPLETED
}
